
language: python

python:
  - 3.5
  - 3.6

services: postgresql

env:
  - TRAVIS: true

before_install:
  - export DJANGO_SETTINGS_MODULE="architect.settings"
  - export PYTHONPATH="$HOME/build/cznewt/architect-api"
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements/test.txt
  - pip install psycopg2 --quiet
  - npm install
  - gem install sass

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput -v 0
  - python manage.py compress
  - pytest
